#Oracle
  # host: localhost
  # port: 1521
  # database SID: XE
  # username: SYSTEM
  # password: oracle

version: '3.8'  

services:
    oracle:
      container_name: oracle-db
      image: carloscastillo/rgt-oracle-xe-11g
      volumes:
        - ./oracle_data:/var/lib/oracle/data
      ports:
        - 1521:1521
      expose:
        - 1521
    cache:
      image: redis:6.2-alpine
      restart: always
      ports:
        - '6379:6379'
      command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      volumes: 
        - ./redis:/data

volumes:
  oracle_data:
    driver: local
  redis:
    driver: local  