-- Drop user
--DROP USER dataSearch CASCADE;

-- Create user
CREATE USER dataSearch IDENTIFIED BY 123456;
GRANT RESOURCE TO dataSearch;
GRANT CONNECT TO dataSearch;
GRANT CREATE VIEW TO dataSearch;
GRANT CREATE SESSION TO dataSearch;
GRANT UNLIMITED TABLESPACE TO dataSearch;
GRANT CREATE JOB TO dataSearch;
GRANT CREATE PROCEDURE TO dataSearch;
GRANT CREATE SEQUENCE TO dataSearch;
GRANT CREATE SYNONYM TO dataSearch ;
GRANT CREATE TABLE TO dataSearch ;
GRANT CREATE TRIGGER TO dataSearch ;
GRANT CREATE TYPE TO dataSearch ;
GRANT CREATE USER TO dataSearch ;
GRANT CREATE CLUSTER TO dataSearch ;
GRANT CREATE INDEXTYPE TO dataSearch ;
GRANT CREATE OPERATOR TO dataSearch ;
GRANT CREATE SESSION TO dataSearch ;
